USE [master]
GO

/****** Object:  Database [ABCTestes]    Script Date: 11/06/2018 14:59:02 ******/
CREATE DATABASE [ABCTestes]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ABCTestes', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\ABCTestes.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'ABCTestes_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\ABCTestes_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [ABCTestes] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ABCTestes].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ABCTestes] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ABCTestes] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ABCTestes] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ABCTestes] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ABCTestes] SET ARITHABORT OFF 
GO

ALTER DATABASE [ABCTestes] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ABCTestes] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ABCTestes] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ABCTestes] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ABCTestes] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ABCTestes] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ABCTestes] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ABCTestes] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ABCTestes] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ABCTestes] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ABCTestes] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ABCTestes] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ABCTestes] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ABCTestes] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ABCTestes] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ABCTestes] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ABCTestes] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ABCTestes] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [ABCTestes] SET  MULTI_USER 
GO

ALTER DATABASE [ABCTestes] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ABCTestes] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ABCTestes] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ABCTestes] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [ABCTestes] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ABCTestes] SET  READ_WRITE 
GO



USE [ABCTestes]
GO

/****** Object:  Table [dbo].[clientes]    Script Date: 11/06/2018 15:01:09 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[clientes](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[CodigoCliente] [nvarchar](max) NOT NULL,
	[NomeCompleto] [nvarchar](150) NOT NULL,
	[NomeEmpresa] [nvarchar](150) NOT NULL,
	[Email] [nvarchar](120) NOT NULL,
	[CNPJ] [nvarchar](15) NOT NULL,
	[TelefoneComercial] [nvarchar](20) NOT NULL,
	[TelefoneCelular] [nvarchar](20) NOT NULL,
	[CEP] [nvarchar](8) NOT NULL,
	[Cidade] [nvarchar](150) NOT NULL,
	[Estado] [nvarchar](25) NOT NULL,
 CONSTRAINT [PK_clientes] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
